# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:

  - package-ecosystem: "npm"
    directory: "/angular"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Europe/Copenhagen"
      
  - package-ecosystem: "pub"
    directory: "/flutter"
    schedule:
      interval: "daily"
      time: "16:00"
      timezone: "Europe/Copenhagen"
