name: Build Angular

on:
  pull_request:
    paths:
      - "angular/*"
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Build
        run: |
          cd angular
          npm ci
          npm run build
