name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.2

      - name: Install npm packages
        run: npm ci
      - name: Run npm build
        run: npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v1
        with:
          name: dist-GITHUB_SHA
          path: dist
