name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.2
      - name: Build and deploy
        run: |
          npm ci
          npm run build
          ./node_modules/.bin/firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
