name: Deploy Angular

on:
  push:
    paths:
      - "angular/*"
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.2

      - name: deploy
        run: |
          cd angular
          npm ci
          npm run build
          ./node_modules/.bin/firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
